#
# Docker compose file to run the full Coeus stack locally
# Access keys are for the IAM user coeus_dev_user
# By default, the dev SQS queues and the dev indexes on the AWS elasticsearch dev/test domain will be used 
# and the device simulator will not be loaded
# Local (docker) elasticsearch instance and simulator can be enabled by uncommenting
# robustini /http://dimafeng.com/2018/12/27/neotypes-1/

version: '3'

networks:
  devnetwork:
    driver: bridge

services:
  neo4j:
    image: neo4j:3.5.0
    ports:
     - "7474:7474"
     - "7687:7687"
    volumes:
     - ./db/dbms:/data/dbms
    networks:
    - devnetwork